version: '3'
services:
    web:
        image: nginx
        container_name: wordpress_app
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./web:/var/www/html"
        command: ["cp -r", "data/plugin/GetResponse", "web/wp-content/plugins"]
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: slummer87/docker-php71-fpm-image
        container_name: wordpress_php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"
        depends_on:
            - mysqldb
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wordpress_phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=localhost
        restart: always
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql
        container_name: wordpress_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=wordpress
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/docker-entrypoint-initdb.d