version: '3'
services:
    web:
        image: nginx
        container_name: grmondo_app
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/Users/rkarkut/Development/projects/grmondo:/var/www/html"
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: slummer87/docker-php7.1-fpm
        container_name: grmondo_php
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./etc/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
            - "/Users/rkarkut/Development/projects/grmondo:/var/www/html"
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:5.7
        container_name: grmondo_mysql
        restart: always
        environment:
            - MYSQL_DATABASE=grmondo
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=dev
        ports:
            - "3307:3306"
        volumes:
            - ./data/mysql:/docker-entrypoint-initdb.d